### ISSUE TITLE
VVM should not use tqdm unless tqdm is installed

### ISSUE THREAD

**Issue by sabotagebeats** [vyperlang/vvm#7]
https://github.com/vyperlang/vvm/blob/1c562ed481c62f706a3b70e2e55675874d23f623/vvm/install.py#L24-L27

**Comment by iamdefinitelyahuman** [comment]
`tqdm` is only required if `vvm.install_vyper` is called with the `show_progress` kwarg set to `True`.  The docstring for this method states that when using `show_progress` you must have installed `tqdm`.  In my mind this isn't an issue, as you can mitigate it by not requesting a progress bar or including `tqdm` as an upstream dependency.

**Comment by fubuloubu** [comment]
Makes sense!
